# Pandas Exercises

In [1]:
import pandas as pd

path = "diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

Read in csv above to a pandas dataframe

In [ ]:
# YOUR CODE HERE
df = pd.read_csv("diabetes.csv",names = names)

Print out the age and class of the 100th patient

In [15]:
# YOUR CODE HERE
print(df.loc[99,['age','class']])

age      31.0
class     1.0
Name: 99, dtype: float64

Write code to figure out how many people are classified as not having diabetes, class is 0

In [7]:
# YOUR CODE HERE
count = (df['class']==0).sum()
print(count)

500

Write code to figure out how many people are classified as having diabetes, class is 1

In [8]:
# YOUR CODE HERE
count_1 = (df['class']==1).sum()
print(count_1)

268

What percent of people have diabetes in the study

In [11]:
# YOUR CODE HERE
percentage = count_1/(count + count_1) * 100
print(percentage)

34.89583333333333

Print out the `"pres"` and `"class"` (no other columns) for the first 5 people

In [13]:
# YOUR CODE HERE
df[['pres','class']].head()

   pres  class
0    72      1
1    66      0
2    64      1
3    66      0
4    40      1

Run the cell below, it will print out the correlation among the columns

In [17]:
df.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

What column has the highest correlation with class? Find the mean() value of that column

In [20]:
# YOUR CODE HERE
mean = df['plas'].mean()
print(mean)

120.89453125

Create a new dataframe with only people that are above the mean found in the above cell.

In [ ]:
# YOUR CODE HERE
new_df = df[df['plas'] > mean]

349

Create a new dataframe that only includes people who are above the average value for each column in the dataset. In other words, find the average value for each column, and then find which users have values above all of these average column values.

In [28]:
# YOUR CODE HERE
new_df2 = df[(df > df.mean()).all(axis=1)]

*Note: the next 3 problems were not explicitly shown in our tutorial—being able to effectively google and look through documentation is a very important coding tool!* ¯\\\_(ツ)_/¯

Ignoring the index (resetting the index to 0) and using the dataframe from the cell above, sort the values based on `"skin"`, `"test"`, and `"pedi"` values in ascending order. Please write this in one line.

In [29]:
# YOUR CODE HERE
new_df2.sort_values(['skin', 'test', 'pedi']).reset_index(drop=0)

    index  preg  plas  pres  skin  test  mass   pedi  age  class
0     236     7   181    84    21   192  35.9  0.586   51      1
1      43     9   171   110    24   240  45.4  0.721   54      1
2     614    11   138    74    26   144  36.1  0.557   50      1
3     546     5   187    76    27   207  43.6  1.034   53      1
4     259    11   155    76    28   150  33.3  1.353   51      1
5     152     9   156    86    28   155  34.3  1.189   42      1
6     603     7   150    78    29   126  35.2  0.692   54      1
7     206     8   196    76    29   280  37.5  0.605   57      1
8     424     8   151    78    32   210  42.9  0.516   36      1
9     215    12   151    70    40   271  41.8  0.742   38      1
10    159    17   163    72    41   114  40.9  0.817   47      1
11    175     8   179    72    42   130  32.7  0.719   36      1
12    612     7   168    88    42   321  38.2  0.787   40      1
13    375    12   140    82    43   325  39.2  0.528   58      1
14    663     9   145    80    46   130  37.9  0.637   40      1
15    458    10   148    84    48   237  37.6  1.001   51      1

Now let's find the 4 largest values for `"age"`

In [30]:
# YOUR CODE HERE
df['age'].nlargest(n=4)

459    81
453    72
666    70
123    69
Name: age, dtype: int64

Now find the smallest 4 values for `"pedi"` and `"plas"` in reverse order (smallest to largest).

In [31]:
# YOUR CODE HERE
df[['pedi', 'plas']].nsmallest(4, ['pedi', 'plas'])

      pedi  plas
268  0.078   102
180  0.084    87
149  0.085    90
567  0.085    92

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=f3d2e979-42f4-4fa4-a66a-116a1c2662d5' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>